### ISSUE TITLE
Feature for set volume level

### ISSUE THREAD

**Issue by aelttil** [iamcanadian2222/MarantzIP#1]
Hi, 
Thanks for your project !!
My example for set volume level

`    def set_volume_level(self, level):
`
`
        if type(level) == int:
`
`
            raise TypeError("Expecting values between 0-70'. Received type:" + type(level))
`
`
        self.write_command("MV" + level +"\r")
`

Regards, 
Alex.

**Comment by joshualyon** [comment]
Thanks for sharing! Feel free to submit a PR with your code changes - I would look at the following submitting the PR though:

- [ ] It looks like the code raises an error even though the proper `int` type is received. I would have expected that to have been in the else condition. 
- [ ] Ideally the value would be checked against the appropriate range for the receiver. 

I can't remember off the top of my head, but I wouldn't be surprised if the volume range is slightly different for different receiver models, so this probably isn't absolutely required.
